#!/bin/bash

SHUTDOWN=" Shutdown"
REBOOT=" Reboot"

OPTIONS="$SHUTDOWN|$REBOOT"

CHOICE="$(echo "$OPTIONS" | tr "|" "\n" | dmenu -i -c -l 2 -bw 4 -p "System Menu: ")"

case "$CHOICE" in
	$SHUTDOWN) systemctl -i poweroff ;;
	$REBOOT) systemctl reboot ;;
esac

