#!/bin/sh

# Keybindings
#  + <Ctrl + d> - Deletes selected image.
#  + <Ctrl + w> - Runs setwall over selected image. (Sets wallpaper)

while read file
do
    case "$1" in
        "C-d")
            rm "$file" ;;
        "C-w")
            setwall "$file" ;;
    esac
done
