#!/bin/sh

################################################################################
# => Monitor
################################################################################

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

################################################################################
# => Config
################################################################################

get_color () {
    ~/.scripts/get-xresources-color "$1"
}

bspc config border_width         2
bspc config window_gap           1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color   "$(get_color bg)"
bspc config active_border_color   "$(get_color green)"
bspc config focused_border_color  "$(get_color blue)"
bspc config presel_feedback_color "$(get_color yellow)"

################################################################################
# => Ininitial State
################################################################################

bspc desktop "^1" -l monocle
bspc desktop "^5" -l monocle

################################################################################
# => Rules
################################################################################

bspc rule -a mpv      desktop="^5" follow=on
bspc rule -a MEGAsync state=floating

bspc rule -a qutebrowser desktop="^1" state=tiled follow=on
bspc rule -a Firefox-esr desktop="^1" state=tiled follow=on
bspc rule -a Chromium    desktop="^1" state=tiled follow=on

bspc rule -a "bspc-float"                state=floating
bspc rule -a "bspc-float-center-wide"    state=floating center=on rectangle=964x364+0+0
bspc rule -a "*:bspc-picture-in-picture" state=floating sticky=on rectangle=299x169+1131+699
