#!/bin/bash

# Usage: birthday [--polybar] [--show] [--edit]
# Simple script to maintain personal birthday polybar module.

BIRTHDAY_SCRIPT=~/.scripts/birthday-reminder
BIRTHDAY_TEMP_FILE=/tmp/birthday-list

if [[ ! -x $BIRTHDAY_SCRIPT ]]
then
    echo "'$BIRTHDAY_SCRIPT' doesn't exist or isn't executable."
    exit 1
fi

function floating_terminal() {
    $TERMINAL -c "Floating Terminal" $*
}

case "$1" in
    --polybar)
        $BIRTHDAY_SCRIPT --polybar ;;
    --show)
        $BIRTHDAY_SCRIPT --sort > $BIRTHDAY_TEMP_FILE
        echo "# vim: filetype=birthday-reminder-list" >> $BIRTHDAY_TEMP_FILE
        floating_terminal $EDITOR $BIRTHDAY_TEMP_FILE & ;;
    --edit)
        floating_terminal $BIRTHDAY_SCRIPT --edit & ;;
    *)
        echo "'$1' is not a valid option for this script."
        exit 1 ;;
esac
