#!/bin/sh

################################################################################
# => Screen resolution
################################################################################

# Use external monitor as the primary one
xrandr --output VGA1 --primary
# Disable laptop's monitor
xrandr --output LVDS1 --off
# Set resolution to 1440x900
xrandr --output VGA1 --mode 1440x900

################################################################################
# => Before starting WM
################################################################################

# Restore wallpaper if there was one
if [ -f "$WALLPAPER_PATH" ]
then
	feh --no-fehbg --bg-max "$WALLPAPER_PATH" --image-bg 000000
fi

xrdb -merge ~/.config/X11/Xresources
xsetroot -cursor_name left_ptr &

#
# -> Startup applications
#

dunst &                         # Notification daemon
flameshot &                     # Screenshots
sxhkd &                         # Hotkey daemon
mpd &                           # Music player daemon
picom &                         # Compositor
nm-applet &                     # NetworkManager System Tray Applet
~/.config/polybar/launch.sh     # Status bar

################################################################################
# => WM
################################################################################

exec bspwm
