#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap           2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a mpv desktop='^5' follow=on

# Default rules
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

get_color () {
    ~/.scripts/get_xresources_color "$1"
}

# Match theme on Xresources
bspc config normal_border_color   "$(get_color background)"
bspc config active_border_color   "$(get_color color2)"
bspc config focused_border_color  "$(get_color color4)"

