#! /bin/sh

################################################################################
# => Monitor
################################################################################

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

################################################################################
# => Config
################################################################################

bspc config border_width         2
bspc config window_gap           2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#
# -> Color
#

get_color () {
    ~/.scripts/get_xresources_color "$1"
}

bspc config normal_border_color   "$(get_color background)"
bspc config active_border_color   "$(get_color color2)"
bspc config focused_border_color  "$(get_color color4)"

################################################################################
# => Rules
################################################################################

bspc rule -a mpv desktop='^5' follow=on
bspc rule -a MEGAsync state=floating # rectangle=300x500+610+25
