#!/bin/bash

open () {
    chromium --disable-gpu --app=$1
}

DISCORD="ﭮ Discord App"
DISCORD_DEV="ﭮ Discord Developer Portal"
GITHUB=" Github"
TWITTER=" Twitter"
FACEBOOK=" Facebook Messages"

OPTIONS="$DISCORD|$DISCORD_DEV|$GITHUB|$TWITTER|$FACEBOOK"

CHOICE="$(echo "$OPTIONS" | tr "|" "\n" | dmenu -i -c -l 4 -bw 4 -p "Open: ")"

case "$CHOICE" in
    $DISCORD) open "https://www.discord.com/app" ;;
    $DISCORD_DEV) open "https://discord.com/developers/applications" ;;
    $GITHUB) open "https://www.github.com" ;;
    $TWITTER) open "https://www.twitter.com" ;;
    $FACEBOOK) open "https://www.facebook.com/messages/t" ;;
esac
